name: Deployment Pipeline

on:
    push:
        branches:
            - main

permissions: write-all

jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps: 
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            
            -   uses: actions/setup-node@v3
                with:
                    node-version: 18

            -   name: Install dependencies
                run: yarn install --no-audit --no-found --no-optional

            -   name: Build
                run: yarn build

            -   name: Test
                run: yarn test

            -   name: Lint
                run: yarn lint

            -   name: Format
                run: yarn format

            -   name: Deploy Netlify
                uses: South-Paw/action-netlify-deploy@v1.2.0
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                    netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
                    build-dir: './dist'
                    draft: true
                    comment-on-commit: true