name: Deployment Pipeline

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps: 
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            
            -   uses: actions/setup-node@v3
                with:
                    node-version: 18
            
            -   name: Install dependencies
                run: yarn install --no-audit --no-found --no-optional

            -   name: Build
                run: yarn build

            -   name: Test
                run: yarn test

            -   name: Deploy Netlify
                uses: danakim/gh-action-deploy-netlify@master
                with:
                  AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                  DEPLOY_PROD: true