name: Deployment Pipeline

on:
    push:
        branches:
            - main

permissions: write-all

jobs:
    avoid_reduncy:
        runs-on: ubuntu-22.04
        steps:
            -   name: Cancel Previus Redundant Builds
                uses: styfle/cancel-workflow-action@0.9.1
                with:
                        access_token: ${{ github.token }}

    lint:
        runs-on: ubuntu-22.04
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            
            -   uses: actions/setup-node@v3
                with:
                    node-version: 18

            -   name: Install dependencies
                run: yarn install --no-audit --no-found --no-optional

            -   name: Lint
                run: yarn lint

    build:
        runs-on: ubuntu-22.04
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            
            -   uses: actions/setup-node@v3
                with:
                    node-version: 18

            -   name: Install dependencies
                run: yarn install --no-audit --no-found --no-optional

            -   name: Build
                run: yarn build

            -   uses: actions/upload-artifact@v2
                with:
                    name: dist
                    path: dist

    test:
        needs: [lint, build]
        runs-on: ubuntu-22.04
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            
            -   uses: actions/setup-node@v3
                with:
                    node-version: 18

            -   name: Install dependencies
                run: yarn install --no-audit --no-found --no-optional

            -   uses: actions/download-artifact@v2
                with:
                    name: dist
                    path: dist
            
            -   name: Test
                run: yarn test
            
    deploy:
        needs: [test]
        runs-on: ubuntu-22.04
        steps: 
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            
            -   uses: actions/setup-node@v3
                with:
                    node-version: 18

            -   name: Install dependencies
                run: yarn install --no-audit --no-found --no-optional

            -   name: Build
                run: yarn build

            -   name: Format
                run: yarn format

            -   name: Deploy Netlify
                uses: South-Paw/action-netlify-deploy@v1.2.0
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                    netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
                    build-dir: './dist'
                    draft: true
                    comment-on-commit: true